### ISSUE TITLE
api.sandbox.coinbase.com:443 open=false

### ISSUE THREAD

**Issue by dheeraj510** [coinbase/coinbase-ruby#91]
Last day I tried using same API using sandbox that worked, but today it is not working and throwing 443 error. below is my sample code. I see below error from sandbox:

```
irb(main):001:0> require 'coinbase/wallet'
=> true
irb(main):002:0> SANDBOX_URL = 'https://api.sandbox.coinbase.com'
=> "https://api.sandbox.coinbase.com"
irb(main):003:0> client = Coinbase::Wallet::Client.new(api_key: "M8NTtZ1XfvUdgpfx",api_secret: "kdIcDMXYK2SMaGWIM6uupc3myvP6OOyg" , api_url: SANDBOX_URL)
=> #<Coinbase::Wallet::Client:0x87d18a8 @api_key="M8NTtZ1XfvUdgpfx", @api_secret="kdIcDMXYK2SMaGWIM6uupc3myvP6OOyg", @api_uri=#<URI::HTTPS:0x87d14e8 URL:https://api.sandbox.coinbase.com>, @conn=#<Net::HTTP api.sandbox.coinbase.com:443 open=false>>
```

Any help please ?

**Comment by Cb-James** [comment]
Hi there,

You may have experienced a 403 error over the last couple of days, but the issue should be resolved now. 443 is the port number, and the code posted above is working as expected.

**Comment by dheeraj510** [comment]
Thanks for reply @Cb-James : 
It is still showing me same error when i tried to use **client.accounts**. This is the error I am getting 

> Coinbase::Wallet::APIError: [403] {}

Please have a look at below code which I am trying:

```
irb(main):001:0> require 'coinbase/wallet'
=> false
irb(main):002:0> SANDBOX_URL = 'https://api.sandbox.coinbase.com'
=> "https://api.sandbox.coinbase.com"
irb(main):003:0> client = Coinbase::Wallet::Client.new(api_key: "M8NTtZ1XfvUdgpfx",api_secret: "kdIcDMXYK2SMaGWIM6uupc3myvP6OOyg" , api_url: SANDBOX_URL)
=> #<Coinbase::Wallet::Client:0xe6a4498 @api_key="M8NTtZ1XfvUdgpfx", @api_secret="kdIcDMXYK2SMaGWIM6uupc3myvP6OOyg", @api_uri=#<URI::HTTPS:0xe6a4380 URL:https://api.sandbox.coinbase.com>, @conn=#<Net::HTTP api.sandbox.coinbase.com:443 open=false>>
irb(main):004:0> client.accounts
Coinbase::Wallet::APIError: [403] {}
	from /home/dheeraj/.rvm/gems/ruby-2.1.5@coinbase/gems/coinbase-4.0.7/lib/coinbase/wallet/api_errors.rb:53:in `check_response_status'
	from /home/dheeraj/.rvm/gems/ruby-2.1.5@coinbase/gems/coinbase-4.0.7/lib/coinbase/wallet/adapters/net_http.rb:36:in `http_verb'
	from /home/dheeraj/.rvm/gems/ruby-2.1.5@coinbase/gems/coinbase-4.0.7/lib/coinbase/wallet/api_client.rb:617:in `get'
	from /home/dheeraj/.rvm/gems/ruby-2.1.5@coinbase/gems/coinbase-4.0.7/lib/coinbase/wallet/api_client.rb:108:in `accounts'
	from (irb):4
	from /home/dheeraj/.rvm/gems/ruby-2.1.5@coinbase/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
	from /home/dheeraj/.rvm/gems/ruby-2.1.5@coinbase/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
	from /home/dheeraj/.rvm/gems/ruby-2.1.5@coinbase/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/dheeraj/.rvm/gems/ruby-2.1.5@coinbase/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/dheeraj/.rvm/gems/ruby-2.1.5@coinbase/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

Is there any limitations that this API will work only in some countries ? currently I am trying it from India

**Comment by Cb-James** [comment]
Hi dheeraj510, sorry for the false hope. I'm told some more adjustments have been made to prevent this from happening. Would you mind trying again at your earliest convenience, and let us know if the problem persists?
